const fs = require('node:fs');
const { initializeTestEnvironment, assertSucceeds, assertFails } = require('@firebase/rules-unit-testing');
const { doc, getDoc, setDoc, updateDoc, collection, getDocs, deleteDoc, writeBatch, serverTimestamp } = require('firebase/firestore');

(async () => {
  const env = await initializeTestEnvironment({ projectId: 'demo-nrd-access', firestore: { rules: fs.readFileSync(require('node:path').resolve(__dirname, '../../firestore.rules'), 'utf8'), host: '127.0.0.1', port: 8088 } });
  const grant = { login: 'ana', enabled: true, profile: true, promotions: false, prices: false };
  try {
    await env.withSecurityRulesDisabled(async ctx => {
      await setDoc(doc(ctx.firestore(), 'restricted_access/ana'), grant);
      await setDoc(doc(ctx.firestore(), 'restricted_access/bia'), { ...grant, login: 'bia', enabled: false });
      await setDoc(doc(ctx.firestore(), 'restricted_access/carla'), { ...grant, login: 'carla', profile: false, prices: true });
      await setDoc(doc(ctx.firestore(), 'work_schedules/2026-10'), { year: 2026, month: 10, employees: [] });
    });
    const master = env.authenticatedContext('master', { email: 'mestre@nrdlojas.com' }).firestore();
    const admin = env.authenticatedContext('admin', { email: 'admin@nrdlojas.com' }).firestore();
    const ana = env.authenticatedContext('ana', { email: 'ana@usuarios.nrdlojas.com' }).firestore();
    const bia = env.authenticatedContext('bia').firestore();
    const carla = env.authenticatedContext('carla').firestore();
    const publicDb = env.unauthenticatedContext().firestore();
    await assertFails(getDoc(doc(publicDb, 'restricted_access/ana')));
    await assertFails(getDoc(doc(publicDb, 'work_schedules/2026-10')));
    await assertSucceeds(getDoc(doc(ana, 'restricted_access/ana')));
    await assertFails(getDoc(doc(ana, 'restricted_access/bia')));
    await assertFails(getDocs(collection(ana, 'restricted_access')));
    await assertFails(updateDoc(doc(ana, 'restricted_access/ana'), { prices: true }));
    await assertFails(setDoc(doc(publicDb, 'restricted_access/new'), grant));
    await assertFails(setDoc(doc(admin, 'restricted_access/new'), grant));
    await assertSucceeds(setDoc(doc(master, 'restricted_access/new'), grant));
    await assertFails(setDoc(doc(master, 'restricted_access/bad'), { ...grant, password: 'never-store-passwords' }));
    await assertSucceeds(getDocs(collection(master, 'restricted_access')));
    await assertSucceeds(getDoc(doc(master, 'work_schedules/2026-10')));
    await assertSucceeds(getDoc(doc(ana, 'work_schedules/2026-10')));
    await assertFails(getDoc(doc(bia, 'work_schedules/2026-10')));
    await assertFails(getDoc(doc(carla, 'work_schedules/2026-10')));
    await assertSucceeds(updateDoc(doc(master, 'restricted_access/ana'), { enabled: false }));
    await assertFails(getDoc(doc(ana, 'work_schedules/2026-10')));
    await assertFails(setDoc(doc(publicDb, 'config/restricted_access'), { publicAccess: true }));
    await assertFails(setDoc(doc(admin, 'config/restricted_access'), { publicAccess: true }));
    await assertFails(setDoc(doc(master, 'config/restricted_access'), { publicAccess: 'true' }));
    await assertSucceeds(setDoc(doc(master, 'config/restricted_access'), { publicAccess: true }));
    await assertSucceeds(getDoc(doc(publicDb, 'work_schedules/2026-10')));
    await assertSucceeds(getDoc(doc(bia, 'work_schedules/2026-10')));
    await assertSucceeds(setDoc(doc(master, 'config/restricted_access'), { publicAccess: false }));
    await assertFails(getDoc(doc(publicDb, 'work_schedules/2026-10')));
    await assertFails(getDoc(doc(ana, 'work_schedules/2026-10')));
    const policy = { enabled: true, minimumVersion: 'v1.0.705' };
    await assertFails(setDoc(doc(publicDb, 'config/update_policy'), policy));
    await assertFails(setDoc(doc(admin, 'config/update_policy'), policy));
    await assertSucceeds(setDoc(doc(master, 'config/update_policy'), policy));
    await assertSucceeds(getDoc(doc(publicDb, 'config/update_policy')));
    await assertFails(setDoc(doc(master, 'config/update_policy'), { enabled: true, minimumVersion: 'garbage' }));
    await assertSucceeds(updateDoc(doc(master, 'config/update_policy'), { enabled: false }));
    await assertFails(getDocs(collection(publicDb, 'restricted_access')));
    await assertFails(getDocs(collection(admin, 'restricted_access')));
    await assertSucceeds(updateDoc(doc(master, 'restricted_access/ana'), { enabled: true, profile: true, promotions: true, prices: false }));
    await assertSucceeds(getDoc(doc(ana, 'work_schedules/2026-10')));
    await assertSucceeds(updateDoc(doc(master, 'restricted_access/ana'), { enabled: true, profile: false, promotions: true, prices: true }));
    await assertFails(getDoc(doc(ana, 'work_schedules/2026-10')));
    await assertFails(updateDoc(doc(admin, 'restricted_access/ana'), { profile: true }));
    await assertFails(deleteDoc(doc(ana, 'restricted_access/ana')));
    await assertFails(deleteDoc(doc(admin, 'restricted_access/ana')));
    await assertFails(deleteDoc(doc(publicDb, 'restricted_access/ana')));
    await assertSucceeds(deleteDoc(doc(master, 'restricted_access/ana')));
    await assertFails(getDoc(doc(ana, 'work_schedules/2026-10')));
    const deviceId = 'a'.repeat(64);
    const eventId = 'b'.repeat(64);
    const installation = { deviceIdHash: deviceId, appVersion: '1.0.708', appVersionCode: 708,
      firstSeenAt: serverTimestamp(), lastSeenAt: serverTimestamp(), platform: 'android' };
    const event = { deviceIdHash: deviceId, appVersion: '1.0.708', appVersionCode: 708,
      firstSeenAt: serverTimestamp(), createdAt: serverTimestamp() };
    const initial = writeBatch(publicDb);
    initial.set(doc(publicDb, 'app_installations/' + deviceId), installation);
    initial.set(doc(publicDb, 'app_installation_events/' + eventId), event);
    await assertSucceeds(initial.commit());
    await assertFails(getDoc(doc(publicDb, 'app_installation_events/' + eventId)));
    await assertFails(getDocs(collection(master, 'app_installation_events')));
    await assertFails(updateDoc(doc(publicDb, 'app_installation_events/' + eventId), { appVersionCode: 999 }));
    await assertFails(deleteDoc(doc(master, 'app_installation_events/' + eventId)));
    await assertFails(setDoc(doc(publicDb, 'app_installation_events/' + 'c'.repeat(64)), { ...event, appVersionCode: 999 }));
    await assertFails(setDoc(doc(publicDb, 'app_installation_deliveries/fake'), { sent: true }));
    await assertFails(getDoc(doc(publicDb, 'app_installation_deliveries/fake')));
    const original = await getDoc(doc(publicDb, 'app_installations/' + deviceId));
    const update = writeBatch(publicDb);
    update.update(doc(publicDb, 'app_installations/' + deviceId), { appVersion: '1.0.709', appVersionCode: 709, lastSeenAt: serverTimestamp() });
    update.set(doc(publicDb, 'app_installation_events/' + 'd'.repeat(64)), { ...event, appVersion: '1.0.709', appVersionCode: 709, firstSeenAt: original.get('firstSeenAt') });
    await assertSucceeds(update.commit());
    // Legacy clients keep their existing heartbeat writes; no new fields required.
    await assertSucceeds(updateDoc(doc(publicDb, 'app_installations/' + deviceId), { lastSeenAt: serverTimestamp() }));
    console.log('PASS: access, update policy, immutable installation events and private delivery security checks.');
  } finally { await env.cleanup(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
